### PR TITLE
fix: remove topP parameter from Bedrock inference config

### LINKED ISSUE #8377: [BUG] Sonnet 4.5 cannot both be specified for this model error message
### Problem (one or two sentences)

When trying to invoke Sonnet 4.5 under Bedrock API, get error message "Sonnet 4.5 cannot both be specified for this model error message". Not sure if it happens as will when invoking Anthropic API

### Context (who is affected and when)

Happens when invoking the freshly released model Sonnet 4.5 under Bedrock API

### Reproduction steps

1) Select Bedrock as API Provider
2) For Model, select anthropic.claude-sonnet-4-5-20250929-v1:0
3) Run a simple task
4) View the error message received

### Expected result

The task starts and provide response

### Actual result

Error Messaeg "the model returned the following errors: temperature and top_p cannot both be specified for this model. Please use only one

### Variations tried (optional)

_No response_

### App Version

3.28.11

### API Provider (optional)

AWS Bedrock

### Model Used (optional)

Claude Sonnet 4.5

### Roo Code Task Links (optional)

_No response_

### Relevant logs or errors (optional)

```shell

```

### PR DESCRIPTION
**Pull request by daniel-lxs**
Fixes #8377

## Changes

- Removed `topP` from `BedrockInferenceConfig` interface
- Removed `topP` assignment in `createMessage()` method  
- Removed `topP` assignment in `completePrompt()` method

## Testing

✅ All 107 Bedrock tests pass including reasoning tests
✅ Type checking passed
✅ Linting passed

## Description

The `topP` parameter was being sent to AWS Bedrock even when extended thinking was enabled, which could cause issues. This PR completely removes the `topP` parameter from the inference configuration, allowing the provider to rely solely on `maxTokens` and `temperature` parameters for both streaming and non-streaming requests.

----

> [!IMPORTANT]
> Remove `topP` parameter from Bedrock inference configuration to prevent issues with extended thinking, updating `bedrock.ts` and related tests.
> 
>   - **Behavior**:
>     - Removed `topP` parameter from `BedrockInferenceConfig` in `bedrock.ts`.
>     - Removed `topP` assignment in `createMessage()` and `completePrompt()` methods in `bedrock.ts`.
>     - Updated tests in `bedrock-reasoning.spec.ts` to verify `topP` is not present in payloads.
>   - **Testing**:
>     - All 107 Bedrock tests pass, including reasoning tests.
>     - Type checking and linting passed.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=RooCodeInc%2FRoo-Code&utm_source=github&utm_medium=referral)<sup> for b5e18c646dc100ebd5c12e5c4082cf05bfb68011. You can [customize](https://app.ellipsis.dev/RooCodeInc/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: src/api/providers/bedrock.ts [hunk 1]
```diff
@@ -44,7 +44,6 @@ import type { SingleCompletionHandler, ApiHandlerCreateMessageMetadata } from ".
 interface BedrockInferenceConfig {
 	maxTokens: number
 	temperature?: number
-	topP?: number
 }
```
Comment (ghost) [inline src/api/providers/bedrock.ts:48]: [P1] Contract change removes topP from BedrockInferenceConfig. Ensure related tests and any call sites that asserted/relied on topP are updated (e.g., src/api/providers/__tests__/bedrock-reasoning.spec.ts expectations when thinking is disabled).

File: src/api/providers/bedrock.ts [hunk 2]
```diff
@@ -647,7 +642,6 @@ export class AwsBedrockHandler extends BaseProvider implements SingleCompletionH
 			const inferenceConfig: BedrockInferenceConfig = {
 				maxTokens: modelConfig.maxTokens || (modelConfig.info.maxTokens as number),
 				temperature: modelConfig.temperature ?? (this.options.modelTemperature as number),
-				...(thinkingEnabled ? {} : { topP: 0.1 }), // Only set topP when thinking is NOT enabled
 			}
```
Comment (ghost) [inline src/api/providers/bedrock.ts:647]: [P2] Non-streaming path mirrors streaming config without topP. Consider adding/adjusting a unit test for completePrompt to assert that inferenceConfig does not include topP, to prevent regressions.

**Review by mrubens — APPROVED** [review]
