### PR TITLE
fix: support full endpoint URLs in OpenAI Compatible provider (#5212)

### LINKED ISSUE #5212: Codebase Indexing with Azure OpenAI: API version missing
### App Version

3.22.4

### API Provider

OpenAI Compatible

### Model Used

text-embedding-3-small

### 🔁 Steps to Reproduce

I am trying to use the codebase indexing feature with my Azure OpenAI embedding model, using the "OpenAI Compatible" provider option ony Windows machine.

I am consistently receiving a 404 Resource not found error, and after debugging, I think I have isolated the cause. The extension is not sending the mandatory api-version query parameter that the Azure OpenAI API requires for all requests.

Here is a summary of my findings:

The Goal: To connect Roo's codebase indexing to an Azure OpenAI deployment endpoint like:
https://[my-resource].openai.azure.com/openai/deployments/[my-deployment]/embeddings?api-version=2023-05-15

The Problem: The settings UI for the "OpenAI Compatible" provider does not have a field to specify the api-version.

The Proof: I used a local Python server to intercept the request from the Roo extension. I found that the extension constructs the final URL by simply taking the "Base URL" from the settings and appending /embeddings. This leaves no way to correctly add the required ?api-version=... parameter for Azure.

This lack of an api-version parameter causes Azure to reject the request, resulting in the 404 error.

Suggested Solution:
Could you please add a dedicated "API Version" field to the "OpenAI Compatible" provider settings? This would allow users to provide the required version (e.g., 2023-05-15) and enable full compatibility with Azure OpenAI.

### 💥 Outcome Summary

 404 Resource not found error

### 📄 Relevant Logs or Errors (Optional)

```shell

```

### PR DESCRIPTION
**Pull request by SannidhyaSah**
## Description

Fixes #5212

This PR resolves the 404 "Resource not found" error when using Azure OpenAI with the RooCode extension's "OpenAI Compatible" provider. The issue occurred because the OpenAI SDK automatically appends `/embeddings` to the base URL, which conflicts with Azure OpenAI's requirement for complete endpoint URLs that include the deployment name and API version.

**Beyond Azure OpenAI**, this enhancement provides broader compatibility with various OpenAI-compatible endpoints that require specific URL structures, making the provider more flexible and robust for diverse deployment scenarios.

## Changes Made

- **Enhanced URL Detection**: Added `isFullEndpointUrl()` method to detect when users provide complete endpoint URLs (containing `/embeddings` or `/deployments/`)
- **Direct HTTP Requests**: Implemented `makeDirectEmbeddingRequest()` for bypassing the OpenAI SDK when full URLs are provided
- **Conditional Logic**: Modified `_embedBatchWithRetries()` to use either the OpenAI SDK or direct fetch based on URL type
- **Universal Compatibility**: Added support for both `api-key` and `Authorization` headers to ensure compatibility with various OpenAI-compatible services
- **Base64 Encoding**: Used `encoding_format: "base64"` for consistent embedding handling across both paths

## Broader Benefits

This solution enhances compatibility with various OpenAI-compatible endpoints beyond just Azure OpenAI:

- **Custom OpenAI Deployments**: Services that require specific endpoint paths or query parameters
- **Proxy Services**: OpenAI-compatible proxies that need complete URLs to route requests correctly
- **Enterprise Deployments**: Internal OpenAI-compatible services with custom URL structures
- **Multi-tenant Services**: Platforms that embed tenant/deployment information in the URL path
- **API Gateways**: Services that require specific URL formats for routing and authentication
- **Local/Self-hosted Models**: OpenAI-compatible local deployments with custom endpoint structures

The intelligent URL detection ensures that:
- **Standard OpenAI endpoints** continue to work exactly as before (backward compatibility)
- **Full endpoint URLs** bypass SDK URL manipulation, preserving query parameters and custom paths
- **Flexible authentication** supports both `api-key` and `Authorization` header patterns
- **Consistent behavior** across different deployment types through unified base64 encoding

## Testing

- [x] All existing tests pass (39/39 tests passing)
- [x] Added comprehensive unit tests for new functionality:
  - URL detection logic for various endpoint formats
  - Direct HTTP request handling with proper headers
  - Azure OpenAI compatibility scenarios
  - Error handling and retry mechanisms
  - Multiple OpenAI-compatible endpoint patterns
- [x] Linting checks pass with no warnings
- [x] Type checking passes across all packages

## Verification of Acceptance Criteria

- [x] **Azure OpenAI Support**: Users can now provide complete Azure OpenAI endpoint URLs including deployment names and API versions
- [x] **Backward Compatibility**: Existing OpenAI and OpenAI-compatible providers continue to work unchanged
- [x] **Error Resolution**: The 404 "Resource not found" error is resolved for Azure OpenAI configurations
- [x] **Universal Headers**: Both `api-key` and `Authorization` headers are included for broad compatibility
- [x] **Enhanced Flexibility**: Support for various OpenAI-compatible endpoint URL structures

## Checklist

- [x] Code follows project style guidelines
- [x] Self-review completed
- [x] Comments added for complex logic
- [x] No breaking changes
- [x] Comprehensive test coverage added
- [x] All existing functionality preserved
- [x] Enhanced compatibility with multiple OpenAI-compatible services

----

> [!IMPORTANT]
> Fixes Azure OpenAI 404 error by supporting full endpoint URLs in `OpenAICompatibleEmbedder`, enhancing compatibility with various OpenAI-compatible services.
> 
>   - **Behavior**:
>     - Fixes 404 error for Azure OpenAI by supporting full endpoint URLs in `OpenAICompatibleEmbedder`.
>     - Adds `isFullEndpointUrl()` to detect full URLs and `makeDirectEmbeddingRequest()` to handle them.
>     - Modifies `_embedBatchWithRetries()` to choose between SDK and direct requests based on URL type.
>     - Supports both `api-key` and `Authorization` headers for broader compatibility.
>     - Ensures consistent base64 encoding for embeddings.
>   - **Testing**:
>     - Adds unit tests in `openai-compatible.spec.ts` for URL detection, direct requests, and error handling.
>     - Tests cover Azure OpenAI scenarios, rate limiting, and multiple endpoint patterns.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=RooCodeInc%2FRoo-Code&utm_source=github&utm_medium=referral)<sup> for 49e775a4f18f5da116c0aba8d05c192714b7cdd2. You can [customize](https://app.ellipsis.dev/RooCodeInc/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by SannidhyaSah** [comment]
i can confirm that this pr is working properly and fixes the issue originally mentioned in #5212
image

File: src/services/code-index/embedders/openai-compatible.ts [hunk 1]
```diff
@@ -119,16 +173,26 @@ export class OpenAICompatibleEmbedder implements IEmbedder {
 		batchTexts: string[],
 		model: string,
 	): Promise<{ embeddings: number[][]; usage: { promptTokens: number; totalTokens: number } }> {
+		const isFullUrl = this.isFullEndpointUrl(this.baseUrl)
```
Comment (daniel-lxs) [inline src/services/code-index/embedders/openai-compatible.ts]: I noticed that `isFullEndpointUrl(this.baseUrl)` is being called on every batch request, but `this.baseUrl` never changes after initialization. This unnecessary repeated computation should be avoided.

Could we compute this once in the constructor and store it as a property? For example:

```typescript
private readonly isFullUrl: boolean;

constructor(baseUrl: string, apiKey: string, modelId?: string) {
    // ... existing validation ...
    this.baseUrl = baseUrl;
    this.apiKey = apiKey;
    this.isFullUrl = this.isFullEndpointUrl(baseUrl);
    // ... rest of constructor ...
}
```

Then use `this.isFullUrl` directly in `_embedBatchWithRetries()` instead of calling the method repeatedly.

File: src/services/code-index/embedders/openai-compatible.ts [hunk 2]
```diff
@@ -109,6 +113,56 @@ export class OpenAICompatibleEmbedder implements IEmbedder {
...
 
+	/**
+	 * Determines if the provided URL is a full endpoint URL (contains /embeddings or /deployments/)
+	 * or a base URL that needs the endpoint appended by the SDK
+	 * @param url The URL to check
+	 * @returns true if it's a full endpoint URL, false if it's a base URL
+	 */
+	private isFullEndpointUrl(url: string): boolean {
+		// Check if the URL contains common embedding endpoint patterns
+		return url.includes("/embeddings") || url.includes("/deployments/")
```
Comment (daniel-lxs) [inline src/services/code-index/embedders/openai-compatible.ts]: The URL detection pattern might be too broad. Could a URL like `https://api.example.com/v1/embeddings-service` or `https://api.example.com/deployments-info/v1` be incorrectly classified as a full endpoint URL?

Would it be safer to use more specific patterns? For example:
- Check if the URL ends with `/embeddings` (with or without query params)
- Use a regex pattern like `/deployments/[^/]+/embeddings` for Azure-style URLs

This would reduce the risk of false positives while maintaining compatibility with the intended services.

File: src/services/code-index/embedders/openai-compatible.ts [hunk 3]
```diff
@@ -109,6 +113,56 @@ export class OpenAICompatibleEmbedder implements IEmbedder {
...
+			body: JSON.stringify({
+				input: batchTexts,
+				model: model,
+				encoding_format: "base64",
+			}),
+		})
+
+		if (!response.ok) {
+			const errorText = await response.text()
+			const error: any = new Error(`HTTP ${response.status}: ${errorText}`)
```
Comment (daniel-lxs) [inline src/services/code-index/embedders/openai-compatible.ts]: Using `any` type here reduces type safety. Could we define a proper error type or at least use a more specific type annotation?

```typescript
interface HttpError extends Error {
    status?: number;
}

const error = new Error(`HTTP ${response.status}: ${errorText}`) as HttpError;
error.status = response.status;
throw error;
```

Also, including the endpoint (without sensitive query params) in the error message would help with debugging:
```typescript
const urlObj = new URL(url);
const sanitizedUrl = `${urlObj.origin}${urlObj.pathname}`;
const error = new Error(`HTTP ${response.status} from ${sanitizedUrl}: ${errorText}`) as HttpError;
```

File: src/services/code-index/embedders/__tests__/openai-compatible.spec.ts [hunk 4]
```diff
@@ -613,5 +616,159 @@ describe("OpenAICompatibleEmbedder", () => {
...
+			describe("URL detection", () => {
+				it.each([
+					[
+						"https://myresource.openai.azure.com/openai/deployments/mymodel/embeddings?api-version=2024-02-01",
+						true,
+					],
+					["https://myresource.openai.azure.com/openai/deployments/text-embedding-ada-002/embeddings", true],
+					["https://api.openai.com/v1", false],
+					["https://api.example.com", false],
+					["http://localhost:8080", false],
```
Comment (daniel-lxs) [inline src/services/code-index/embedders/__tests__/openai-compatible.spec.ts:662]: Good test coverage for URL detection! However, it would be valuable to add test cases for potential false positives to ensure the detection logic is robust:

```typescript
// Additional test cases for edge cases
["https://api.example.com/v1/embeddings-service", false],  // Contains 'embeddings' but not as endpoint
["https://api.example.com/deployments-info/v1", false],    // Contains 'deployments' but not in correct pattern
["https://api.example.com/v1/models/embeddings", false],   // 'embeddings' in wrong position
```

These tests would help ensure the URL detection doesn't accidentally match unintended patterns.

**Review by daniel-lxs — COMMENTED** [review]
Hey @SannidhyaSah I left a couple of suggestions that are worth taking a look at.

Let me know what you think.

**Comment by SannidhyaSah** [comment]
@daniel-lxs I've made the changes mentioned in the review.
