### PR TITLE
Fix duplicate rehydrate during reasoning; centralize rehydrate and preserve cancel metadata

### LINKED ISSUE #8153: [BUG] Cancel during response can blank conversation history (chat locks)
## Type
Bug

## Problem / Value
Cancelling a running response can leave the task in a broken state and wipe the stored conversation for that task. The chat box becomes unusable until the task is closed and reopened, disrupting work.

## Context
Version: v3.22.5 • API Provider: anthropic • Model: sonnet-3.5.
Occurs when clicking Cancel during the model’s “thinking/streaming” phase. Intermittent but reproducible with timing. Affects anyone who cancels mid‑response.
Current behavior: the task may hang; the conversation history file is written as an empty list, and the chat input becomes unusable. Logs show “Found API conversation history file, but it’s empty (parsed as []).”

## Expected behavior
Cancelling a task should not corrupt or clear the conversation history, and the chat should remain usable.

## Reproduction
1) Start a task with the model
2) While the model is responding (especially during “thinking”)
3) Click the Cancel button
4) Observe the task may hang and the chat box becomes unusable
5) Logs show the empty conversation history message

## Constraints/Preferences
Use safe read‑modify‑write transactions (from PR #5332) for files defined in GlobalFileNames to prevent file corruption when in‑memory state is empty during a race condition.

### PR DESCRIPTION
**Pull request by hannesrudolph**
Closes #8153 

Before:

https://github.com/user-attachments/assets/649ed77f-1e8b-4a9a-b33d-2dd8386e0722

AFTER

https://github.com/user-attachments/assets/3ca6d13f-3e07-44d0-90a3-2f8578721be0

Problem
- Users occasionally saw a duplicate/overlaid task after pressing “Cancel” or after a mid-stream network failure—most visibly during “reasoning” streaming.
- Root cause: two independent rehydration paths racing:
  - Task-level catch during the streaming loop rehydrated from history
    [Task.recursivelyMakeClineRequests()](src/core/task/Task.ts:2181)
  - Provider cancel path also rehydrated from history
    [ClineProvider.cancelTask()](src/core/webview/ClineProvider.ts:2519)
- This race was easier to hit during reasoning because reasoning chunks are UI-only (persisted to clineMessages) and not added to apiConversationHistory mid-stream, so the Task catch reached rehydrate faster.

Changes
1) Centralize rehydration in the Provider
   - Removed Task-side rehydrate in the streaming error/cancel catch; the Task now:
     - Persists an interruption marker first
     - Sets an explicit abortReason
     - Calls abortTask() and emits TaskAborted
     - Does not call createTaskWithHistoryItem
   - Provider listens for TaskAborted and rehydrates only for streaming failures (not user-cancels)
     [Task.recursivelyMakeClineRequests()](src/core/task/Task.ts:2181)
     [ClineProvider.onTaskAborted](src/core/webview/ClineProvider.ts:197)

2) Prevent double-create by marking “abandoned” earlier on user-cancel
   - Set task.abortReason = "user_cancelled" and mark the current Task instance abandoned immediately after abortTask(), before waiting for the stream to drain
     [ClineProvider.cancelTask()](src/core/webview/ClineProvider.ts:2534)
   - This ensures the Task catch never tries to rehydrate.

3) Provider-side cancel bookkeeping to mirror abortStream for user cancels
   - Because setting abandoned early can skip abortStream on user-cancel, the Provider now fills the same persistence gaps:
     - Update the last say("api_req_started") UI row with cancelReason = "user_cancelled"
       [ClineProvider.cancelTask()](src/core/webview/ClineProvider.ts:2561)
     - Append an assistant “Response interrupted by user” marker to apiConversationHistory when appropriate
       [ClineProvider.cancelTask()](src/core/webview/ClineProvider.ts:2561)
   - This preserves UI/API consistency and cancellation telemetry without reintroducing the race.

4) Resume reconciliation for UI-only reasoning
   - On resuming from history, remove trailing reasoning-only UI rows that never entered apiConversationHistory (orphan partials)
     [Task.resumeTaskFromHistory()](src/core/task/Task.ts:1267)

5) Defensive safeguards to avoid rehydrate after rehydrate
   - Before rehydrating on TaskAborted (streaming_failed) or after cancel wait, check if the current instance already changed; skip if so
     [ClineProvider.onTaskAborted](src/core/webview/ClineProvider.ts:197)
     [ClineProvider.cancelTask()](src/core/webview/ClineProvider.ts:2534)

Why this approach
- Eliminates the duplicate/overlay by making the Provider the single source of rehydration truth.
- Maintains a coherent timeline when cancelling mid-reasoning by explicitly persisting:
  - cancelReason into the last api_req_started row
  - an assistant “interrupted by user” entry into API history
- Keeps normal success flows unchanged and produces a clean resume prompt consistently.

Behavioral impact
- Cancel during reasoning: one rehydrate, no duplicates; cancelReason and interruption marker preserved.
- Network failure mid-stream: Task emits TaskAborted with abortReason="streaming_failed"; Provider rehydrates once.
- Cancel during text streaming: one rehydrate; no duplicates.
- didFinishAbortingStream may not set on user-cancel (due to early abandoned), but Provider waits on other safe conditions and applies the same persistence updates Provider-side.

Key references
- Removed Task-side rehydrate:
  [Task.recursivelyMakeClineRequests()](src/core/task/Task.ts:2181)
- Provider-owned rehydrate and cancel bookkeeping:
  [ClineProvider.onTaskAborted](src/core/webview/ClineProvider.ts:197)
  [ClineProvider.cancelTask()](src/core/webview/ClineProvider.ts:2534)
- Resume reasoning reconciliation:
  [Task.resumeTaskFromHistory()](src/core/task/Task.ts:1267)

----

> [!IMPORTANT]
> Centralizes task rehydration in `ClineProvider.ts` to prevent duplicate rehydration during reasoning and updates localization for interruption messages.
> 
>   - **Behavior**:
>     - Centralizes rehydration in `ClineProvider.ts`, removing task-side rehydration in `Task.ts`.
>     - `ClineProvider.ts` now handles rehydration only for streaming failures, not user cancels.
>     - Marks tasks as "abandoned" earlier on user-cancel to prevent double rehydration.
>     - Updates UI/API consistency by appending interruption markers to `apiConversationHistory`.
>   - **Files**:
>     - `Task.ts`: Removes task-side rehydration logic, adds `abortReason` property.
>     - `ClineProvider.ts`: Implements centralized rehydration logic, updates cancel bookkeeping.
>     - Localization files: Adds interruption messages for user and API error interruptions.
>   - **Misc**:
>     - Ensures no rehydration occurs if the task instance has already changed.
>     - Improves handling of reasoning-only UI rows during task resumption.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=RooCodeInc%2FRoo-Code&utm_source=github&utm_medium=referral)<sup> for b1958e873da1235371892b5db5f9d613e6e00553. You can [customize](https://app.ellipsis.dev/RooCodeInc/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by hannesrudolph** [comment]
Summary of applied fixes (items 1–6)

Implemented
1) Mark the original instance as abandoned (not getCurrentTask)
- Updated to set the concrete task’s flag, avoiding incorrect instance marking.
- See [ClineProvider.cancelTask()](src/core/webview/ClineProvider.ts:2572)

2) Guard JSON parsing and centralize cancel bookkeeping
- Replaced ad‑hoc fs/JSON.parse with safe helpers that read/write through the persistence layer.
- New helpers:
  - [addCancelReasonToLastApiReqStarted](src/core/task-persistence/cancelBookkeeping.ts:6)
  - [appendAssistantInterruptionIfNeeded](src/core/task-persistence/cancelBookkeeping.ts:35)
- Call sites:
  - [ClineProvider.cancelTask()](src/core/webview/ClineProvider.ts:2616)

3) Final race re-check before rehydrate
- Added a second instanceId equality check immediately before rehydration to avoid duplicate rehydrate.
- See [ClineProvider.cancelTask()](src/core/webview/ClineProvider.ts:2669)

4) Remove any-cast for abortReason
- Use strongly-typed property on Task instance instead of (instance as any).abortReason.
- See [ClineProvider.onTaskAborted](src/core/webview/ClineProvider.ts:205)

5) Centralize user-facing interruption strings (prep for i18n)
- New constants: [messages.ts](src/shared/messages.ts:6)
- Replaced hard-coded strings:
  - [Task.recursivelyMakeClineRequests() → abortStream label usage](src/core/task/Task.ts:1899)
  - [ClineProvider.cancelTask() assistant interruption](src/core/webview/ClineProvider.ts:2639)

6) Deduplicate cancel bookkeeping logic
- Extracted shared logic into persistence helpers to keep a single source of truth.
- See [cancelBookkeeping.ts](src/core/task-persistence/cancelBookkeeping.ts:1)

Additional cleanup
- Removed unused destructured variable (apiConversationHistoryFilePath).
  - [ClineProvider.cancelTask()](src/core/webview/ClineProvider.ts:2556)

Notes
- The ‘reasoning cleanup’ hard-cap suggestion was not implemented (only items 1–6 were requested). The existing loop already terminates on first non-reasoning row and is linear in length; adding a cap remains possible if desired.

CI
- Pushed changes to branch fix/reasoning-cancel-centralized-rehydrate. Checks are now pending.

File: src/shared/messages.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+/**
+ * Centralized user-facing message constants for interruption labels.
+ * TODO: Consider moving these to i18n JSON in src/i18n/locales/* and wiring through t()
+ * so they can be localized consistently across the UI.
+ *
+ * Note: These are plain phrases (no surrounding brackets). Call sites add any desired decoration.
+ */
+export const RESPONSE_INTERRUPTED_BY_USER = "Response interrupted by user"
```
Comment (daniel-lxs) [inline src/shared/messages.ts:8]: These need to be internationalized

File: src/core/task-persistence/cancelBookkeeping.ts [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+
+		if (revIdx === -1) {
+			return
+		}
+
+		const idx = uiMsgs.length - 1 - revIdx
+
+		try {
+			const existing = uiMsgs[idx]?.text ? JSON.parse(uiMsgs[idx].text as string) : {}
+			uiMsgs[idx].text = JSON.stringify({ ...existing, cancelReason: reason })
```
Comment (daniel-lxs) [inline src/core/task-persistence/cancelBookkeeping.ts:35]: Should we check if there's already a reason here before overwriting?

**Review by daniel-lxs — APPROVED** [review]

**Review by mrubens — APPROVED** [review]
