### PR TITLE
fix: resolve diff editor issues with markdown preview associations (#4946)

### LINKED ISSUE #2360: Automatic detection and handling of Markdown Preview conflict when using write_to_file tool
### App Version

3.11.8

### API Provider

OpenRouter

### Model Used

Any

### Actual vs. Expected Behavior

**Problem:**
When the VS Code setting for Markdown preview ("workbench.editorAssociations": { "*.md": "vscode.markdown.preview.editor" }) is enabled, the write_to_file tool consistently fails to write content to .md files due to conflicts with the Markdown Preview.

**Expected Behavior:**
The app should automatically detect if a Markdown file is being opened in Preview mode, and circumvent this by either:

Using the "Open With..." command internally to ensure the file opens in standard editing mode.

Temporarily overriding or bypassing the Markdown Preview mode when performing write operations.

**Current Behavior:**

Files can be created but remain blank.

An error message is displayed:

Failed to open diff editor, please try again...

**Steps to Reproduce:**

Enable the following settings in VS Code:

"markdown.preview.openMarkdownLinks": "inPreview",
"workbench.editorAssociations": { "*.md": "vscode.markdown.preview.editor" }

Attempt to use write_to_file to save generated markdown content.

**Suggested Solutions:**

Implement internal logic to check file editor associations before writing.

Automatically use "Open With..." in standard editing mode when .md files are targeted by write_to_file.

**Additional Context:**
This issue occurs regardless of model or provider (OpenRouter, Anthropic, Gemini). Disabling diff mode or experimental features does not resolve the issue. Removing the Markdown Preview settings manually resolves the problem temporarily but reduces usability for users who prefer the preview mode by default.

### Detailed Steps to Reproduce

1.
2.
3.

### Relevant API Request Output

```shell

```

### Additional Context

_No response_

### LINKED ISSUE #4946: Cannot use apply diff, write to file, or search and replace. Claude Sonnet 4 OR.
### App Version

3.21.1

### API Provider

OpenRouter

### Model Used

Claude 4.0 Sonnet (& Devstral Small in further testing)

### 🔁 Steps to Reproduce

I am unable to use apply diff, search and replace, and write to file (unsure if these are the same tools) at all. Ubuntu 22.04.

Image

`TASKS.md` is 14 lines and 203 tokens.  In the screenshot example I just asked Orchestrator for the completed tasks to be marked off and it switched to Code mode. This happens all of the time, whether at the start or mid flow of runs (mentioned as important detail on Reddit). I am new to RooCode so I have never seen this work. I am not using experimental concurrent file edits. It happens when creating files, trying to place text inside empty files, or modify existing files. Sometimes it falls back to using a command to place text which works, or to Desktop Commander MCP which I read on the subreddit was a workaround for this. I would prefer to use the built in tools for this. I have restarted Windsurf and my computer several times but this continues. Probably not relevant but qdrant and nomic-embed-text are running locally. Can you please tell me how I can resolve this?

### 💥 Outcome Summary

The attempts to create or modify files always fail.

### 📄 Relevant Logs or Errors (Optional)

```shell

```

### PR DESCRIPTION
**Pull request by daniel-lxs**
## Description

Fixes #2360

This PR resolves an issue where file editing tools (apply_diff, write_to_file, search_and_replace) fail for files that have custom editor associations configured in VS Code, particularly markdown files with preview mode associations.

## Root Cause

When VS Code has `workbench.editorAssociations` configured to open certain file types (like `"*.md": "vscode.markdown.preview.editor"`), the `vscode.diff` command opens the file in preview mode instead of as an editable text document. This causes:

1. "Illegal value for lineNumber" errors when trying to edit
2. Diff views that can't be properly detected and closed

## Solution

Implemented a simple and reliable approach:

1. **Pre-open files as text documents**: Before executing the diff command, always call `vscode.window.showTextDocument()` with `preview: false` to ensure the file opens in text editing mode
2. **Enhanced diff view detection**: Updated `closeAllDiffViews()` to identify diff tabs both by URI scheme and by label pattern ("↔ Roo's Changes")

This PR doesn't affect the normal behavior of editing files at all. Files were being opened when edited, but this happened after the edit itself. Now it happens before the edit. Ultimately, the result is exactly the same.

## Changes Made

- **`src/integrations/editor/DiffViewProvider.ts`**:
  - Modified `openDiffEditor()` to pre-open files as text documents before executing diff command
  - Enhanced `closeAllDiffViews()` to detect diff views by label pattern as fallback
  - Added comprehensive comments explaining the fix

- **`src/integrations/editor/__tests__/DiffViewProvider.spec.ts`**:
  - Updated mocks to include all required VSCode APIs
  - Added tests verifying the pre-opening behavior
  - Added tests for enhanced diff view closing logic
  - All existing tests continue to pass

## Testing

- [x] All existing tests pass
- [x] Added new tests for pre-opening behavior
- [x] Added tests for enhanced diff view detection
- [x] Manual testing with markdown files and preview associations
- [x] Verified no performance regression

## Verification of Acceptance Criteria

- [x] File editing tools work correctly with markdown files that have preview associations
- [x] Diff views are properly opened and closed
- [x] No "Illegal value for lineNumber" errors
- [x] Solution works for all file types, not just markdown
- [x] Backward compatibility maintained

## Impact

- **Positive**: Fixes a blocking issue for users with custom editor associations
- **Performance**: Minimal impact - adds one additional `showTextDocument` call per diff operation
- **Compatibility**: Fully backward compatible, no breaking changes
- **Scope**: Affects only the diff editor functionality

## Screenshots/Demo

Before: File editing tools would fail with "Illegal value for lineNumber" errors for markdown files with preview associations.

After: File editing tools work seamlessly regardless of editor associations.

## Checklist

- [x] Code follows project style guidelines
- [x] Self-review completed
- [x] Comments added for complex logic
- [x] All tests pass
- [x] No breaking changes
- [x] Issue requirements fully addressed

----

> [!IMPORTANT]
> Fixes diff editor issues in VS Code by pre-opening files as text documents and enhancing diff view detection.
> 
>   - **Behavior**:
>     - Fixes issue with `vscode.diff` command opening files in preview mode due to `workbench.editorAssociations`.
>     - Pre-opens files as text documents using `vscode.window.showTextDocument()` with `preview: false`.
>     - Enhances `closeAllDiffViews()` in `DiffViewProvider.ts` to detect diff views by URI scheme and label pattern.
>   - **Testing**:
>     - Updates `DiffViewProvider.spec.ts` to mock necessary VSCode APIs.
>     - Adds tests for pre-opening behavior and enhanced diff view detection.
>     - Verifies no performance regression and maintains backward compatibility.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=RooCodeInc%2FRoo-Code&utm_source=github&utm_medium=referral)<sup> for 7909ee1bee12245683858b9ef5e300fd99c11f93. You can [customize](https://app.ellipsis.dev/RooCodeInc/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: src/integrations/editor/DiffViewProvider.ts [hunk 1]
```diff
@@ -384,12 +384,25 @@ export class DiffViewProvider {
...
-			)
+					!tab.isDirty
+				) {
+					return true
+				}
+
+				// Also check by tab label for our specific diff views
+				// This catches cases where the diff view might be created differently
+				// when files are pre-opened as text documents
+				if (tab.label.includes("↔ Roo's Changes") && !tab.isDirty) {
```
Comment (mrubens) [inline src/integrations/editor/DiffViewProvider.ts]: Can we make this "↔ Roo's Changes" a shared constant somewhere to make sure we don't break this logic if we ever change the string?

**Review by mrubens — APPROVED** [review]
Looks good other than the comment about using a constant for `Original ↔ Roo's Changes` and looking for that

**Review by mrubens — APPROVED** [review]
