### PR TITLE
fix: preserve user input when selecting follow-up choices

### LINKED ISSUE #7316: Messages at choices disappear.
### App Version

3.25.21

### API Provider

Not Applicable / Other

### Model Used

N/A

### Roo Code Task Links (Optional)

Often times when I write a message at a choice prompt, the message is deleted and not seen in the chat, or the history. The message also is not it in the up-key message history.

### 🔁 Steps to Reproduce

It is not consistent, at a choice prompt write a message, that message is lost.

### 💥 Outcome Summary

Expected the choice to be respected and the message to be appended to my choice.

### PR DESCRIPTION
**Pull request by daniel-lxs**
## Description

This PR fixes an issue where user messages were disappearing when selecting follow-up choices at choice prompts.

## Problem
When users typed a message at a choice prompt and then selected a follow-up suggestion, their typed message was being cleared and lost. The message was not visible in the chat history and was not available in the up-key message history.

## Solution
The fix preserves the user's input value in the text area after sending the follow-up choice message. This ensures that what the user typed remains visible and accessible.

## Changes
- Modified the `handleFollowUpClick` function in `ChatView.tsx` to preserve the input value when sending follow-up choices
- Added `inputValue` to the dependency array of the `handleFollowUpClick` callback

## Testing
- Tested that user input is preserved when selecting follow-up choices
- Verified that the message history works correctly
- Confirmed that the fix doesn't affect other chat functionality

Fixes #7316

### CODE REVIEW

File: webview-ui/src/components/chat/ChatView.tsx [hunk 1]
```diff
@@ -1493,10 +1493,23 @@ const ChatViewComponent: React.ForwardRefRenderFunction<ChatViewRef, ChatViewPro
 					return currentValue !== "" ? `${currentValue} \n${suggestion.answer}` : suggestion.answer
 				})
 			} else {
+				// Don't clear the input value when sending a follow-up choice
+				// The message should be sent but the text area should preserve what the user typed
+				const preservedInput = inputValue
```
Comment (ghost) [inline webview-ui/src/components/chat/ChatView.tsx]: This implementation has a fundamental issue - it preserves the input value AFTER sending the message, which means the user's typed text remains in the input field even after selecting a follow-up choice. 

Based on the issue description, the expected behavior should be one of:
1. Combine the user's typed text with the follow-up choice before sending
2. Send the typed text as a separate parameter along with the follow-up
3. Store the typed text in message history before clearing

The current approach of preserving and restoring after `handleSendMessage` could also lead to race conditions since that function triggers state updates and async operations.

Could you reconsider the approach here?

File: webview-ui/src/components/chat/ChatView.tsx [hunk 2]
```diff
@@ -1493,10 +1493,23 @@ const ChatViewComponent: React.ForwardRefRenderFunction<ChatViewRef, ChatViewPro
 					return currentValue !== "" ? `${currentValue} \n${suggestion.answer}` : suggestion.answer
 				})
 			} else {
+				// Don't clear the input value when sending a follow-up choice
```
Comment (ghost) [inline webview-ui/src/components/chat/ChatView.tsx:1502]: This comment is misleading - the code actually clears the input value (via `handleSendMessage`) and then restores it, rather than preventing it from being cleared. Consider updating the comment to accurately reflect what's happening:

```suggestion
// Preserve and restore the input value after sending the follow-up choice
// This ensures the user's typed text remains visible in the input field
```

File: webview-ui/src/components/chat/ChatView.tsx (hunk 1 above)
Comment (daniel-lxs) [reply webview-ui/src/components/chat/ChatView.tsx]: This is the way to solve the issue, preserve whatever you are typing but send the choice

File: webview-ui/src/components/chat/ChatView.tsx (hunk 2 above)
Comment (daniel-lxs) [reply webview-ui/src/components/chat/ChatView.tsx:1502]: Yeah whatever

File: webview-ui/src/components/chat/ChatView.tsx [hunk 3]
```diff
@@ -1493,10 +1493,23 @@ const ChatViewComponent: React.ForwardRefRenderFunction<ChatViewRef, ChatViewPro
...
 		},
-		[handleSendMessage, setInputValue, switchToMode, alwaysAllowModeSwitch, clineAsk, markFollowUpAsAnswered],
+		[
+			handleSendMessage,
+			setInputValue,
+			switchToMode,
+			alwaysAllowModeSwitch,
+			clineAsk,
+			markFollowUpAsAnswered,
+			inputValue,
```
[the remark this answers is not in the document]
Comment (daniel-lxs) [reply webview-ui/src/components/chat/ChatView.tsx]: Done

**Review by mrubens — APPROVED** [review]
